### ISSUE TITLE
Example dataset

### ISSUE THREAD

**Issue by liyuxuan89** [wulalago/AgentSPL#1]
Great repository, 

I'm wondering Is there an example dataset for the code. I'd like to run the code.

Thanks

**Comment by wulalago** [comment]
> Great repository,
> 
> I'm wondering Is there an example dataset for the code. I'd like to run the code.
> 
> Thanks

Thanks for your interest, I am a little busy this period. But definitely, I will prepare an example data and upload it asap.

**Comment by wrq9335** [comment]
> > Great repository,
> > I'm wondering Is there an example dataset for the code. I'd like to run the code.
> > Thanks
> 
> Thanks for your interest, I am a little busy this period. But definitely, I will prepare an example data and upload it asap.

33/5000 
Hello, could you please provide us with an example data? Or can you tell me the content and format of the plane parameters?
“info.npz  # contain the information (plane parameters)  ”

**Comment by wrq9335** [comment]
> > Great repository,
> > I'm wondering Is there an example dataset for the code. I'd like to run the code.
> > Thanks
> 
> Thanks for your interest, I am a little busy this period. But definitely, I will prepare an example data and upload it asap.

Hello, could you please provide us with an example data? Or can you tell me the content and format of the plane parameters?
“info.npz # contain the information (plane parameters) ”

**Comment by wulalago** [comment]
> Great repository,
> 
> I'm wondering Is there an example dataset for the code. I'd like to run the code.
> 
> Thanks

I have uploaded an example data into this repo.
