### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Yuyalan** [wulalago/AgentSPL#2]
Great work!BTW after reading your research and paper I found that they are greatly helpful to my research.
But it's hard for me to get some useful and proper data like those you use in your research.
So I wanna know if you can share your data with me?
I'll appreciate it if I can get your reply!
Thaks again!

**Comment by wulalago** [comment]
> Great work!BTW after reading your research and paper I found that they are greatly helpful to my research. But it's hard for me to get some useful and proper data like those you use in your research. So I wanna know if you can share your data with me? I'll appreciate it if I can get your reply! Thaks again!

Thanks for your interest. I am sorry the dataset is private and I have already left the original Lab. Contact Dr. Yang or Prof. Ni for any data collaboration. I suggest you can try to find any other public CT/MRI dataset with landmark annotation, which can be also formulated as the standard plane localization task.
