### ISSUE TITLE
An example data or the content and format of the plane parameters

### ISSUE THREAD

**Issue by wrq9335** [wulalago/AgentSPL#4]
Hello, could you please provide us with an example data? Or can you tell me the content and format of the plane parameters?
“info.npz # contain the information (plane parameters) ”

**Comment by wulalago** [comment]
> Hello, could you please provide us with an example data? Or can you tell me the content and format of the plane parameters? “info.npz # contain the information (plane parameters) ”

I have uploaded the relevant example data into this repo. Please have a look

**Comment by wrq9335** [comment]
> > Hello, could you please provide us with an example data? Or can you tell me the content and format of the plane parameters? “info.npz # contain the information (plane parameters) ”
> 
> I have uploaded the relevant example data into this repo. Please have a look

Thank you very much. You are so kind
